# ===================================================================
# Profile for MariaDB storage
# ===================================================================
spring:
  # DATASOURCE
  datasource: 
    platform: mysql
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MYSQL_DATASOURCE_URL:jdbc:mysql://localhost/webfront?autoReconnect=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    show-sql: ${DEBUG_SHOWSQL:false}
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        globally_quoted_identifiers: true
