# ===================================================================
# Profile on OpenShift v3
# ===================================================================
# disable Eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
ribbon:
  eureka:
    enabled: false
# define backend host
woofer-backend:
  ribbon:
    listOfServers: backend:${BACKEND_SERVICE_PORT}
