# ===================================================================
# Profile for shipping logs to multiple logging management systems
# ===================================================================
logging:
  config: classpath:logback-multi.xml

custom:
  access_log:
    config: logback-access-multi.xml
  logging:
    principal:
      # hash_algo: hashcode
      hash_algo: none
