# ===================================================================
# Profile for activating distributed tracing with Zipkin
# ===================================================================
spring:
  zipkin:
    enabled: true
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
  sleuth:
    sampler:
      percentage: ${ZIPKIN_SAMPLING:0.1}
