# ===================================================================
# Profile for H2 storage
# ===================================================================
spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: ${H2_DATASOURCE_URL:jdbc:h2:mem:backend;MODE=MySQL;DATABASE_TO_UPPER=TRUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS \"public\";}
    username: ${H2_USER:sa}
    password: ${H2_PASSWORD:}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
      path: /manage/h2
      settings:
        web-allow-others: true
